// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFi49JdPEV9Dw7Hi0dVjh-aRXLnACGprY',
    appId: '1:959900525065:web:ed866d09b3b7dee3614ed8',
    messagingSenderId: '959900525065',
    projectId: 'flutter-login-c2825',
    authDomain: 'flutter-login-c2825.firebaseapp.com',
    databaseURL: 'https://flutter-login-c2825-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-c2825.appspot.com',
    measurementId: 'G-5HSQ833FT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShmlYfDc7T0eAz6Dc5M5q0yATwHs67lQ',
    appId: '1:959900525065:android:f8728ea704ade653614ed8',
    messagingSenderId: '959900525065',
    projectId: 'flutter-login-c2825',
    databaseURL: 'https://flutter-login-c2825-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-c2825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjjk83U06PRdkEUYs-mjsHVl6fuTbuCQ',
    appId: '1:959900525065:ios:16424ec65efb6d62614ed8',
    messagingSenderId: '959900525065',
    projectId: 'flutter-login-c2825',
    databaseURL: 'https://flutter-login-c2825-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-c2825.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZjjk83U06PRdkEUYs-mjsHVl6fuTbuCQ',
    appId: '1:959900525065:ios:16424ec65efb6d62614ed8',
    messagingSenderId: '959900525065',
    projectId: 'flutter-login-c2825',
    databaseURL: 'https://flutter-login-c2825-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-c2825.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFi49JdPEV9Dw7Hi0dVjh-aRXLnACGprY',
    appId: '1:959900525065:web:ba41fdc531039e31614ed8',
    messagingSenderId: '959900525065',
    projectId: 'flutter-login-c2825',
    authDomain: 'flutter-login-c2825.firebaseapp.com',
    databaseURL: 'https://flutter-login-c2825-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-login-c2825.appspot.com',
    measurementId: 'G-70CMTZBVVW',
  );
}
